version: '3.8'

services:

  blog:
    container_name: ${COMPOSE_PROJECT_NAME}-python
    tty: true
    build:
      args:
        version: "${PYTHON_IMAGE_VERSION}"
        workdir: "/root/${COMPOSE_PROJECT_NAME}"
      context: ../../
      dockerfile: ./local/docker/python/Dockerfile
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ../../:/root/${COMPOSE_PROJECT_NAME}/
